name: Build Matrix

on:
  workflow_call:

jobs:
  build:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
