name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '**.lock'
      - '.nvmrc'
      - '.vscode/**'
      - '.prettierignore'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '**.lock'
      - '.nvmrc'
      - '.vscode/**'
      - '.prettierignore'
      - '.github/**'
  workflow_call:

jobs:
  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Check formatting
        run: yarn format:check

  lint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    needs: format-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
      - name: Run ESLint
        run: npx eslint .
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  build:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
