name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/fermium, lts/gallium, lts/hydrogen]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn

      - name: Run tests
        run: yarn test
