name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '**.lock'
      - '.nvmrc'
      - '.vscode/**'
      - '.prettierignore'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '**.lock'
      - '.nvmrc'
      - '.vscode/**'
      - '.prettierignore'
      - '.github/**'
  workflow_call:

jobs:
  code-quality:
    name: Code Quality
    uses: ./.github/workflows/code-quality.yml

  build:
    name: Build
    needs: code-quality
    uses: ./.github/workflows/build-matrix.yml
